version: '3'
services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - /mnt/cache/docker-volumes/invidious/postgres:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    env_file:
      - invidious.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
    networks:
      - backend
  invidious:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    networks:
      - backend
      - hetzner-cloud_frontend
    env_file:
      - invidious.env
    environment:
       INVIDIOUS_CONFIG: |
         registration_enabled: true
         channel_threads: 1
         check_tables: true
         feed_threads: 1
         db:
           dbname: changeme
           user: changeme
           password: changeme
           host: postgres
           port: 5432
         full_refresh: false
         external_port: 443
         https_only: true
         domain: changeme
    depends_on:
      - postgres
networks:
  backend:
  hetzner-cloud_frontend:
     external: true
